version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/init.d:/docker-entrypoint-initdb.d
      - ./docker/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: udemy_user
      POSTGRES_PASSWORD: udemy_pass
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
      POSTGRES_DB: udemydb
    hostname: postgres
    restart: always
    user: root

  pgadmin:                     # ← ここが追加分
    image: dpage/pgadmin4:latest   # タグ省略でも latest
    container_name: pgadmin4
    ports:
      - "5050:80"              # ブラウザ http://localhost:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres               # Postgres が立ち上がるまで待つ
    restart: always

